SELECT now () AS UTC現在時間

CREATE DATABASE SQL_TUTORIAL;

DROP DATABASE SQL_TUTORIAL;

DROP TABLE student;
DROP TABLE artist;
DROP TABLE city;

CREATE TABLE IF NOT EXISTS student(
	student_id SERIAL PRIMARY KEY,
	name VARCHAR(20),
	major VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS artists(
	id SERIAL PRIMARY KEY,
	name VARCHAR 
);

SELECT *
FROM artists;

CREATE TABLE IF NOT EXISTS city(
	id SERIAL PRIMARY KEY,
	population VARCHAR
);

CREATE TABLE IF NOT EXISTS city(
	id SERIAL,
	name VARCHAR,
	population INT,
	PRIMARY KEY(id)
);

SELECT *
FROM city;
