SELECT now () AS UTC現在時間

CREATE DATABASE SQL_TUTORIAL;

DROP DATABASE SQL_TUTORIAL;

DROP TABLE student;

CREATE TABLE IF NOT EXISTS student(
	student_id SERIAL PRIMARY KEY,
	name VARCHAR(20),
	major VARCHAR(20)
);